config/routes.rb
Rails.application.routes.draw do  
  resources :memberships, only: [:create, :destroy]
  resources :events
  resources :attendances, only: [:create, :destroy]

  resources :users, only: [:show]

  resources :groups do 
    resources :events, only: [:new, :show]
  end

  devise_for :users, path: '', path_names: { sign_up: 'signup', sign_in: 'login', sign_out: 'logout' }, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root 'welcome#index'
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :interests, format: { with: /\A[\w\W]+\z/ }, allow_blank: true
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]

  # def index
  #   @groups = current_user.groups
  # end

  def create
    @membership = Membership.new(membership_params)

    if @membership.save
      redirect_to group_path(@membership.group_id)
    else
      flash[:alert] = "There was a problem submitting your request. Please try again."
      redirect_to groups_path
    end
  end

  def destroy 
    @membership = Membership.find_by(user_id: current_user.id, group_id: params[:id])
    @membership.destroy
    redirect_to root_path
  end

  private

  def membership_params
    params.require(:membership).permit(:interests, :user_id, :group_id)
  end
end

app/views/memberships/_form.html.erb
<%= simple_form_for membership, url: memberships_path, method: :post do |f| %>
  <%= f.hidden_field :user_id %>
  <%= f.hidden_field :group_id %>

  <div class="field">
    <label class="label">What topics would you like to discuss at events? (optional)</label>
    <div class="control">
      <%= f.input :interests,
                  required: false,
                  label: false,
                  wrapper: false,
                  input_html: { class: "textarea" } %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.button :submit, 'Join group', class:'button cta has-text-white has-text-weight-medium' %>
    </div>
  </div>   
<% end %>

app/views/memberships/index.html.erb
<section class="hero is-medium is-light">
  <div class="hero-body memberships">
    <div class="container">
      <h1 class="title is-size-1-tablet has-text-weight-bold">
        Memberships
      </h1>
    </div>
  </div>
</section>

<div class="page-block">
  
    <div class="columns">
      <div class="column">
        <h4 class="is-size-4 has-text-weight-medium">All Groups</h4>
        <% if @groups.empty? %>
          <h3>It doesn't look like you're a member of any groups yet.</h3>
          <p>Visit our <%= link_to 'Explore Groups', groups_path %> page to find your crowd, and join them! You can also <%= link_to 'start a new group', new_group_path %>.</p>
        <% end %>

        <ul>
          <% @groups.each do |group| %>
            <li><%= link_to group.name, group_path(group) %></li>
          <% end %>
        </ul>      
      </div>

      <div class="column">
        <h4 class="is-size-4 has-text-weight-medium">Groups You Manage</h4>
        <ul>
          <% @groups.each do |group| %>
            <li><%= link_to group.name, group_path(group) %></li>
          <% end %>
        </ul>    
      </div>
    </div>
</div>