config/routes.rb
Rails.application.routes.draw do  
  resources :memberships, only: [:create, :destroy]
  resources :events
  resources :attendances, only: [:create, :destroy]

  resources :users, only: [:show]

  resources :groups do 
    resources :events, only: [:new, :show]
  end

  devise_for :users, path: '', path_names: { sign_up: 'signup', sign_in: 'login', sign_out: 'logout' }, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root 'welcome#index'
end

app/models/group.rb
class Group < ApplicationRecord
  ## Associations
  has_many :events, dependent: :destroy
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships

  ## Validations
  validates_presence_of :name, :description, :city, :state
  validates_uniqueness_of :name, message: 'name has already been taken'
  validates :city, city: true

  def add_creator_to_members(current_user)
    self.users << current_user if current_user.email
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :require_creator, only: [:edit, :update, :destroy]

  def index 
    @groups = Group.all
  end

  def show
    @events = @group.events.upcoming
    @users = @group.users
  end

  def new
    @group = Group.new(creator: current_user.id)
  end

  def create 
    @group = Group.new(group_params)

    if @group.save
      # @group.users << current_user
      add_creator_to_members(current_user)
      redirect_to group_path(@group)
    else
      render :new
    end
  end

  def edit 
  end

  def update
    @group.update(group_params)

    if @group.save
      redirect_to group_path(@group)
    else
      render :edit
    end
  end

  def destroy
    @group.destroy
    redirect_to groups_path
  end

  private

    def group_params
      params.require(:group).permit(:name, :description, :city, :state, :creator)
    end

    def set_group
      @group = Group.find(params[:id])
    end

    def require_creator
      if user_signed_in? && (@group.creator != current_user.id)
        flash[:alert] = "You don't have permission to view that page"
        redirect_to root_path
      end
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def creator_options(group)
    if is_creator(group)
      "<hr>".html_safe +
      (link_to 'Add Event', new_group_event_path(group), class: 'button is-small') + " " +
      (link_to 'Edit', edit_group_path(group), class: 'button is-small is-light is-link') + " " +
      (link_to 'Delete', group_path(group), method: :delete, data: { confirm: "Are you sure you want to delete #{group.name}?" }, class: 'button is-small is-light is-danger')
    end
  end

  def is_creator(group)
    true if user_signed_in? && (group.creator == current_user.id)
  end

  def creator_name(group)
   @user = User.find_by(id: group.creator)
   (link_to first_name(@user), user_path(@user), class: 'has-text-weight-medium') if @user
  end

  def role(group)
    if user.id == user.group.creator
      "Creator"
    else
      "Member"
    end
  end

  def become_member(group)
    if user_signed_in?
      @current_membership = Membership.find_by(user_id: current_user.id, group_id: group.id)

      if @current_membership || is_creator(group)
        "&nbsp;".html_safe
      else 
        @membership = Membership.new(user_id: current_user.id, group_id: group.id)
        "<h4 class='title is-4 has-text-weight-medium is-italic'>Join Us</h4>".html_safe + (render 'memberships/form', membership: @membership)
      end
    end
  end
  
  # def become_member(group)
  #   @current_membership = Membership.find_by(user_id: current_user.id, group_id: group.id)

  #   if @current_membership
  #     "<hr>".html_safe +
  #     (link_to 'Leave group', membership_path(@current_membership), method: :delete, data: { confirm: "Are you sure you want to leave #{group.name}?" }, class: 'button is-small is-danger is-light')
  #   else 
  #     @membership = Membership.new(user_id: current_user.id, group_id: group.id)
  #     "<h3>Join Us</h3><br>".html_safe + (render 'memberships/form', membership: @membership)
  #   end
  # end
end

app/views/groups/_form.html.erb
<p class="subtitle is-7">Fields marked with <span class="notice">*</span> are required</p><br>

<%= simple_form_for group do |f| %>
  <%= f.hidden_field :creator %>

  <div class="field">
    <label class="label">Group name<span class="notice">*</span></label>
    <div class="control">
      <%= f.input :name,
                  required: true,
                  autofocus: true,
                  label: false,
                  wrapper: false,
                  input_html: { class: "input" } %>
    </div>
  </div>

  <div class="field">
    <label class="label">Description<span class="notice">*</span></label>
    <div class="control">
      <%= f.input :description,
                  required: true,
                  label: false,
                  wrapper: false,
                  placeholder: 'A brief intro about your group, and any other information you think is important for people to know before joining your group.',
                  input_html: { class: "textarea" } %>
    </div>
  </div>

  <div class="field">
    <label class="label">Where is your group based from?<span class="notice">*</span></label>
  </div>

  <div class="field is-grouped">
    <div class="control">
      <%= f.input :city,
                  required: true,
                  label: false,
                  placeholder: 'City',
                  wrapper: false,
                  input_html: { class: "input" } %>
    </div>
    <div class="control">
      <span class="select">
        <%= f.input_field :state,
                      collection: states,
                      required: true,
                      label: false,
                      prompt: 'State',
                      input_html: { class: "input" } %>
        <%= f.error :state %>
      </span>     
    </div>
  </div>

  <div class="field is-grouped">
    <div class="control">
      <%= f.submit (@group.new_record? ? 'Submit' : 'Update'), class:'button cta has-text-white has-text-weight-medium' %>
      <%= link_to 'Cancel', groups_path, class:'button is-light is-link' %>
    </div>
  </div> 
<% end %>

app/views/groups/edit.html.erb
<div class="page-block">
  <h1>Edit your group</h1>

  <%= render 'form', group: @group %>
</div>

app/views/groups/index.html.erb
<section class="hero is-medium is-light">
  <div class="hero-body groups">
    <div class="container">
      <h1 class="title is-size-1-tablet has-text-weight-bold">
        Explore Groups
      </h1>
    </div>
  </div>
</section>

<div class="page-block">
  <%= @groups.each do |group| %>
    <h5 class="title is-5"><%= link_to group.name, group_path(group) %></h5>
    
    <div class="columns is-mobile is-gapless subtitle is-size-7 has-text-weight-medium">      
      <div class="column is-narrow">
        <i class="fas fa-map-marker-alt notice"></i><br>
        <i class="fas fa-user-friends notice"></i>
      </div>

      <div class="column">
        <%= city_state(group) %><br>
        <%= count_users(group) %>        
      </div>
    </div>

    <p><%= group.description %></p>
    <!-- <%= creator_options(group) %> -->
    
    <hr>
  <% end %>
</div>

app/views/groups/new.html.erb
<section class="hero is-medium is-light">
  <div class="hero-body new-group">
    <div class="container">
      <h1 class="title is-size-1-tablet has-text-weight-bold">
        Start a new group
      </h1>
    </div>
  </div>
</section>

<div class="page-block">
  <h1></h1>

  <%= render 'form', group: @group %>
</div>

app/views/groups/show.html.erb
<div class="page-block">
  <h3 class="title is-3 has-text-weight-bold"><%= @group.name %></h3>

  <div class="columns is-mobile is-gapless is-size-6">      
    <div class="column is-narrow">
      <i class="fas fa-map-marker-alt notice"></i><br>
      <i class="fas fa-user-friends notice"></i><br>
      <i class="fas fa-user notice"></i>
    </div>

    <div class="column">
      <%= city_state(@group) %><br>
      <%= count_users(@group) %><br>
      Created by <%= creator_name(@group) %>    
    </div>
  </div>

  <hr>

  <h4 class="is-size-4 has-text-weight-medium is-italic">What We're About</h4>
  <p><%= @group.description %></p>
  <br>

  <h4 class="is-size-4 has-text-weight-medium is-italic">Our Events</h4> 
  <ul>
  <% @events.each do |event| %>
    <li>
      <%= link_to event.name, group_event_path(@group, event), class: "has-text-weight-bold" %><br>
      <%= date(event) %> at <%= start_time(event) %>
    </li>    
  <% end %>
  </ul>
  <br>

  <h4 class="is-size-4 has-text-weight-medium is-italic">Our Members</h4>
  <ul>
    <%= @users.each do |user| %>
      <li><%= link_to first_name(user), user_path(user) %></li>
    <% end %>
  </ul>
  <br>

  <!-- New membership form -->
  <p><%= become_member(@group) %></p>

  <%= creator_options(@group) %>
</div>