config/routes.rb
Rails.application.routes.draw do  
  resources :memberships, only: [:create, :destroy]
  resources :events
  resources :attendances, only: [:create, :destroy]

  resources :users, only: [:show]

  resources :groups do 
    resources :events, only: [:new, :show]
  end

  devise_for :users, path: '', path_names: { sign_up: 'signup', sign_in: 'login', sign_out: 'logout' }, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root 'welcome#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :recoverable, :confirmable, :lockable, :timeoutable, and :trackable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]


  ## Associations
  has_many :memberships, dependent: :destroy
  has_many :groups, through: :memberships

  has_many :attendances, dependent: :destroy
  has_many :events, through: :attendances


  ## Validations
  validates_presence_of :name, :email, :password_confirmation
  validates_uniqueness_of :email, message: 'an account with this email has already been created'

  private

    ## OmniAuth Google - called in controllers/users/omniauth_callbacks_controller.rb
    def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        # user.password = 'Devise.friendly_token[0,20]'
        user.password = 'password'
        user.name = auth.info.name
      end
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.google_data'] = request.env['omniauth.auth'].except(:extra)
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @groups = @user.groups
    @events = @user.events.past
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def first_name(user)
    user.name.split.first
  end

  def count_groups(user)
    pluralize(user.groups.count, 'Group')
  end

  def count_events(user)
    pluralize(user.events.past.count, 'Event')
  end

  def role(user, group)
    user.id == group.creator ? "Creator" : "Member"
  end

  
end

app/views/users/show.html.erb
<div class="page-block">
  <h1 class="title is-1 is-spaced has-text-weight-bold"><%= @user.name %></h1>
  <p class="subtitle is-6"><strong>Location:</strong> <%= city_state(@user) %></p>
  <hr>

  <h4 class="is-size-4 has-text-weight-medium">Member of <%= count_groups(@user) %></h4>
  <ul>
    <% @groups.each do |group| %>
      <li><%= link_to group.name, group_path(group), class: "has-text-weight-semibold" %> <span class="is-size-7">(<%= role(@user, group) %>)</span><br>
      </li>
    <% end%>
  </ul>
  <br>

  <h4 class="is-size-4 has-text-weight-medium">Attended <%= count_events(@user) %></h4>
  <ul>
    <% @events.each do |event| %>
      <li><%= link_to event.name, event_path(event), class: "has-text-weight-semibold" %> <br>
      </li>
    <% end%>
  </ul>
  
</div>