config/routes.rb
Rails.application.routes.draw do  
  resources :memberships, only: [:create, :destroy]
  resources :events
  resources :attendances, only: [:create, :destroy]

  resources :users, only: [:show]

  resources :groups do 
    resources :events, only: [:new, :show]
  end

  devise_for :users, path: '', path_names: { sign_up: 'signup', sign_in: 'login', sign_out: 'logout' }, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root 'welcome#index'
end

app/views/shared/_active_nav.html.erb
<!-- navbar for logged in users -->

<% if current_user %>
  <div class="navbar-item has-dropdown is-hoverable">
    <li class="navbar-link"><%= link_to 'Start New Group', new_group_path %></li>

    <div class="navbar-dropdown is-right">
      <li class="navbar-item"><%= link_to 'Create an Event', new_event_path %></li>
    </div>
  </div>

  <div class="navbar-item has-dropdown is-hoverable">
    <li class="navbar-link"><%= link_to "#{first_name(current_user)}'s Profile", user_path(current_user) %></li>

    <div class="navbar-dropdown is-right">
      <li class="navbar-item"><%= link_to 'Account Settings', edit_user_registration_path %></li>
      <li class="navbar-item"><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
    </div>
  </div>
<% end %>

app/views/shared/_inactive_nav.html.erb
<!-- navbar for users not logged in -->

<% if !user_signed_in? %>
  <div class="buttons are-small">                
    <li class="button is-link is-light"><%= link_to 'Log in', new_user_session_path, class: "is-size-6 has-text-grey-dark has-text-weight-medium" %></li>
    <li class="button cta"><%= link_to ' Sign up ', new_user_registration_path, class: "is-size-6 has-text-white has-text-weight-bold" %></li>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="dropdown navigation">
  <div class="container">
    <div class="navbar-brand">
      <li class="navbar-item is-size-5 has-text-weight-semibold"><i class="fas fa-link"></i><%= link_to 'LinkUp', root_path %></li>
      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div> <!-- end of navbar-brand -->


    <div id="navbarBasicExample" class="navbar-menu has-text-weight-medium">

      <div class="navbar-start">          
        <li class="navbar-item"><%= link_to 'Explore Groups', groups_path %></li>
        <li class="navbar-item"><%= link_to 'Find Events', events_path %></li>
      </div> 

      <div class="navbar-end">
        <%= render 'shared/active_nav' %>
        <%= render 'shared/inactive_nav' %>
      </div> <!-- end of navbar-end --> 
    </div> <!-- end of navbar-menu -->  
  </div> <!-- end of container -->
</nav>